### ISSUE TITLE
Bar Chart Horizontal Pagination

### ISSUE THREAD

**Issue by ilmarinen** [microsoft/BackwardCompatibilityML#33] opened 2020-10-21 18:37 UTC
1. If there are a large number of classes shown, then we should display a maximum of n (settable, with default value 5) classes per page of the bar chart.

2. There should be controls for switching between the pages of classes on the bar chart.

**Comment by jlema** [comment] 2020-10-21 18:59
Dupe of #28

**Closed** 2020-10-21 18:59 UTC
Labels: enhancement
